import type { CreateWorkoutInput, ListWorkoutsInput, UpdateWorkoutInput } from "./workout.schemas";
export type WorkoutRow = { id: string; performed_at: string; exercise: string; sets: number; repetitions: number; weight: number | null; notes: string | null; created_at: string; updated_at: string };
export class WorkoutRepository {
  constructor(private readonly db: D1Database) {}
  async findById(userId: string, id: string) { return this.db.prepare("SELECT id,performed_at,exercise,sets,repetitions,weight,notes,created_at,updated_at FROM workouts WHERE user_id=?1 AND id=?2").bind(userId, id).first<WorkoutRow>(); }
  async list(userId: string, input: ListWorkoutsInput): Promise<WorkoutRow[]> { const conditions = ["user_id=?1"]; const values: unknown[] = [userId]; let index = 2; if (input.from) { conditions.push(`performed_at>=?${index}`); values.push(input.from); index++; } if (input.to) { conditions.push(`performed_at<=?${index}`); values.push(input.to); index++; } if (input.exercise) { conditions.push(`exercise LIKE ?${index}`); values.push(`%${input.exercise}%`); index++; } values.push(input.limit, input.offset); return (await this.db.prepare(`SELECT id,performed_at,exercise,sets,repetitions,weight,notes,created_at,updated_at FROM workouts WHERE ${conditions.join(" AND ")} ORDER BY performed_at DESC,created_at DESC LIMIT ?${index} OFFSET ?${index + 1}`).bind(...values).all<WorkoutRow>()).results; }
  async create(userId: string, input: CreateWorkoutInput, id: string, timestamp: string) { await this.db.prepare("INSERT INTO workouts (id,user_id,performed_at,exercise,sets,repetitions,weight,notes,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?9)").bind(id,userId,input.performed_at,input.exercise,input.sets,input.repetitions,input.weight ?? null,input.notes ?? null,timestamp).run(); return (await this.findById(userId,id))!; }
  async update(userId: string, id: string, input: UpdateWorkoutInput, timestamp: string) { const current = await this.findById(userId,id); if (!current) return null; await this.db.prepare("UPDATE workouts SET performed_at=?1,exercise=?2,sets=?3,repetitions=?4,weight=?5,notes=?6,updated_at=?7 WHERE user_id=?8 AND id=?9").bind(input.performed_at ?? current.performed_at,input.exercise ?? current.exercise,input.sets ?? current.sets,input.repetitions ?? current.repetitions,input.weight === undefined ? current.weight : input.weight,input.notes === undefined ? current.notes : input.notes,timestamp,userId,id).run(); return this.findById(userId,id); }
  async delete(userId: string,id: string) { return (await this.db.prepare("DELETE FROM workouts WHERE user_id=?1 AND id=?2").bind(userId,id).run()).meta.changes > 0; }
}
