import type { CreateNoteInput, ListNotesInput, UpdateNoteInput } from "./note.schemas";
export type NoteRow = { id:string; title:string; content:string; created_at:string; updated_at:string; tags:string[] };
type BaseNote = Omit<NoteRow,"tags">;
export class NoteRepository {
  constructor(private readonly db:D1Database) {}
  private async withTags(row:BaseNote|null):Promise<NoteRow|null>{if(!row)return null;const result=await this.db.prepare("SELECT t.name FROM tags t JOIN note_tags nt ON nt.tag_id=t.id WHERE nt.note_id=?1 ORDER BY t.name").bind(row.id).all<{name:string}>();return {...row,tags:result.results.map(tag=>tag.name)};}
  async findById(userId:string,id:string){return this.withTags(await this.db.prepare("SELECT id,title,content,created_at,updated_at FROM notes WHERE user_id=?1 AND id=?2").bind(userId,id).first<BaseNote>());}
  async list(userId:string,input:ListNotesInput):Promise<NoteRow[]>{const conditions=["n.user_id=?1"];const values:unknown[]=[userId];let index=2;if(input.search){conditions.push(`(n.title LIKE ?${index} OR n.content LIKE ?${index})`);values.push(`%${input.search}%`);index++;}if(input.tag){conditions.push(`EXISTS (SELECT 1 FROM note_tags nt2 JOIN tags t2 ON t2.id=nt2.tag_id WHERE nt2.note_id=n.id AND t2.user_id=n.user_id AND t2.name=?${index})`);values.push(input.tag);index++;}values.push(input.limit,input.offset);const rows=(await this.db.prepare(`SELECT n.id,n.title,n.content,n.created_at,n.updated_at FROM notes n WHERE ${conditions.join(" AND ")} ORDER BY n.updated_at DESC LIMIT ?${index} OFFSET ?${index+1}`).bind(...values).all<BaseNote>()).results;return (await Promise.all(rows.map(row=>this.withTags(row)))).filter((row):row is NoteRow=>row!==null);}
  private async syncTags(userId:string,noteId:string,names:string[]){await this.db.prepare("DELETE FROM note_tags WHERE note_id=?1").bind(noteId).run();for(const name of [...new Set(names.map(tag=>tag.trim()).filter(Boolean))]){await this.db.prepare("INSERT INTO tags (id,user_id,name,created_at) VALUES (?1,?2,?3,?4) ON CONFLICT(user_id,name) DO NOTHING").bind(crypto.randomUUID(),userId,name,new Date().toISOString()).run();const tag=await this.db.prepare("SELECT id FROM tags WHERE user_id=?1 AND name=?2").bind(userId,name).first<{id:string}>();if(tag)await this.db.prepare("INSERT OR IGNORE INTO note_tags (note_id,tag_id) VALUES (?1,?2)").bind(noteId,tag.id).run();}}
  async create(userId:string,input:CreateNoteInput,id:string,timestamp:string){await this.db.prepare("INSERT INTO notes (id,user_id,title,content,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?5)").bind(id,userId,input.title,input.content,timestamp).run();await this.syncTags(userId,id,input.tags??[]);return (await this.findById(userId,id))!;}
  async update(userId:string,id:string,input:UpdateNoteInput,timestamp:string){const current=await this.findById(userId,id);if(!current)return null;await this.db.prepare("UPDATE notes SET title=?1,content=?2,updated_at=?3 WHERE user_id=?4 AND id=?5").bind(input.title??current.title,input.content??current.content,timestamp,userId,id).run();if(input.tags!==undefined)await this.syncTags(userId,id,input.tags);return this.findById(userId,id);}
  async delete(userId:string,id:string){return(await this.db.prepare("DELETE FROM notes WHERE user_id=?1 AND id=?2").bind(userId,id).run()).meta.changes>0;}
}
